# Generated by Django 4.2.17 on 2025-07-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
        ('academics', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='counseling_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselors', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='department_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department'),
        ),
    ]
