# Generated by Django 4.2.17 on 2025-07-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_alter_admissionstudent_admission_policy_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='last_exam_roll',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
