# Generated by Django 4.2.17 on 2025-07-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_admissionstudent_last_exam_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='last_exam_registration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/applicant/'),
        ),
    ]
